name: Update Flex endpoint

on:
    workflow_call:
        inputs:
            branch:
                default: main
                required: false
                type: string
            contrib:
                required: false
                type: boolean
            versions_json:
                required: false
                type: string

jobs:
    flex-update:
        name: Update Flex endpoint
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout
                uses: actions/checkout@v4
                id: checkout
                with:
                    fetch-depth: 0

            -
                name: Install tools
                run: |
                    git config --global user.email ""
                    git config --global user.name "github-action[bot]"
                    cd .github
                    wget -q -O recipes-checker.zip https://codeload.github.com/pocky/recipes-checker/zip/refs/heads/feat/multline-for-add-lines
                    unzip recipes-checker.zip
                    cd recipes-checker-feat-multline-for-add-lines
                    composer install --ansi --no-dev

            -
                name: Update Flex endpoint
                run: |
                    mkdir .github/flex-endpoint
                    git ls-tree HEAD */*/* | php .github/recipes-checker-feat-multline-for-add-lines/run generate:flex-endpoint ${{ github.repository }} ${{ inputs.branch }} flex/main .github/flex-endpoint ${{ inputs.versions_json }} ${{ inputs.contrib && '--contrib' || '' }}
                    git switch flex/main
                    git rm -q *.json
                    mv .github/flex-endpoint/*.json .
                    git add *.json
                    cp -a .github/flex-endpoint/archived .
                    git add archived/
                    php .github/recipes-checker-feat-multline-for-add-lines/run generate:recipes-readme index.json ${{ inputs.contrib && '--contrib' || '' }} > RECIPES.md
                    git add RECIPES.md
                    git commit -m 'Update Flex endpoint' || true
                    git push origin -f flex/main